# Multi-table transfer configuration
# Define multiple tables with their relationships and constraints

tables:
  # Parent table - no foreign keys
  - source_table: "ContractAdjustment"
    target_table: "TEST_RLCIS_CONTRACTADJUSTMENT"
    source_schema: "dbo"
    custom_query: ""  # Use default query, or specify custom SQL file
    batch_size: 1000
    
    # Primary key definition
    primary_key: 
    
    # Indexes to create
    indexes:
      - name: 
        columns: []
        unique: false
    
    # No foreign keys for parent table
    foreign_keys: []

  - source_table: "ContractDLO"
    target_table: "TEST_RLCIS_CONTRACTDLO"
    source_schema: "dbo"
    custom_query: ""  # Use default query, or specify custom SQL file
    batch_size: 1000
    
    # Primary key definition
    primary_key: 
    
    # Indexes to create
    indexes:
      - name: 
        columns: []
        unique: false
    
    # No foreign keys for parent table
    foreign_keys: []

  - source_table: "ContractHQ"
    target_table: "TEST_RLCIS_CONTRACTHQ"
    source_schema: "dbo"
    custom_query: ""  # Use default query, or specify custom SQL file
    batch_size: 1000
    
    # Primary key definition
    primary_key: 
    
    # Indexes to create
    indexes:
      - name: 
        columns: []
        unique: false
    
    # No foreign keys for parent table
    foreign_keys: []

  - source_table: "ContractItemHQ"
    target_table: "TEST_RLCIS_CONTRACTITEMHQ"
    source_schema: "dbo"
    custom_query: ""  # Use default query, or specify custom SQL file
    batch_size: 1000
    
    # Primary key definition
    primary_key: 
    
    # Indexes to create
    indexes:
      - name: 
        columns: []
        unique: false
    
    # No foreign keys for parent table
    foreign_keys: []

  - source_table: "Contractor"
    target_table: "TEST_RLCIS_CONTRACTOR"
    source_schema: "dbo"
    custom_query: ""  # Use default query, or specify custom SQL file
    batch_size: 1000
    
    # Primary key definition
    primary_key: 
    
    # Indexes to create
    indexes:
      - name: 
        columns: []
        unique: false
    
    # No foreign keys for parent table
    foreign_keys: []

    

# Global settings
settings:
  # Default batch size for all tables
  default_batch_size: 1000
  
  # Enable/disable foreign key creation
  create_foreign_keys: false
  
  # Enable/disable index creation
  create_indexes: false
  
  # Drop and recreate tables
  drop_existing_tables: true
  
  # Verify data after transfer
  verify_transfers: true
  
  # Data quality check settings
  data_quality_checks:
    # Enable/disable data quality checks after transfer
    enabled: true
    
    # Row count comparison - check if target has same number of rows as source
    row_count_check: true
    
    # Column content comparison - sample and compare content between source and target
    content_comparison:
      enabled: true
      # Percentage of rows to sample for content comparison (0.1 = 10%)
      sample_percentage: 0.1
      # Minimum number of rows to sample (regardless of percentage)
      min_sample_size: 10
      # Maximum number of rows to sample (to avoid excessive processing)
      max_sample_size: 10000
    
    # Quality check results table name in Oracle
    results_table_name: "DATA_QUALITY_CHECKING_RLCIS"