# Multi-table transfer configuration
# Define multiple tables with their relationships and constraints

tables:
  # Parent table - no foreign keys
  - source_table: "ContractAdjustment"
    target_table: "RLCIS_CONTRACTADJUSTMENT"
    source_schema: "dbo"
    custom_query: ""  # Use default query, or specify custom SQL file
    batch_size: 1000
    
    # Primary key definition
    primary_key: 
    
    # Indexes to create
    indexes:
      - name: 
        columns: []
        unique: false
    
    # No foreign keys for parent table
    foreign_keys: []

  - source_table: "ContractDLO"
    target_table: "RLCIS_CONTRACTDLO"
    source_schema: "dbo"
    custom_query: ""  # Use default query, or specify custom SQL file
    batch_size: 1000
    
    # Primary key definition
    primary_key: 
    
    # Indexes to create
    indexes:
      - name: 
        columns: []
        unique: false
    
    # No foreign keys for parent table
    foreign_keys: []

  - source_table: "ContractHQ"
    target_table: "RLCIS_CONTRACTHQ"
    source_schema: "dbo"
    custom_query: ""  # Use default query, or specify custom SQL file
    batch_size: 1000
    
    # Primary key definition
    primary_key: 
    
    # Indexes to create
    indexes:
      - name: 
        columns: []
        unique: false
    
    # No foreign keys for parent table
    foreign_keys: []

  - source_table: "ContractItemHQ"
    target_table: "RLCIS_CONTRACTITEMHQ"
    source_schema: "dbo"
    custom_query: ""  # Use default query, or specify custom SQL file
    batch_size: 1000
    
    # Primary key definition
    primary_key: 
    
    # Indexes to create
    indexes:
      - name: 
        columns: []
        unique: false
    
    # No foreign keys for parent table
    foreign_keys: []

  - source_table: "Contractor"
    target_table: "RLCIS_CONTRACTOR"
    source_schema: "dbo"
    custom_query: ""  # Use default query, or specify custom SQL file
    batch_size: 1000
    
    # Primary key definition
    primary_key: 
    
    # Indexes to create
    indexes:
      - name: 
        columns: []
        unique: false
    
    # No foreign keys for parent table
    foreign_keys: []

    

# Global settings
settings:
  # Default batch size for all tables
  default_batch_size: 1000
  
  # Enable/disable foreign key creation
  create_foreign_keys: false
  
  # Enable/disable index creation
  create_indexes: false
  
  # Drop and recreate tables
  drop_existing_tables: true
  
  # Verify data after transfer
  verify_transfers: true